version: "3"
services:
  db:
    image: mariadb:latest
    environment:
      - MYSQL_ROOT_PASSWORD=mariadb
      - MYSQL_DATABASE=mariadb
      - MYSQL_USER=mariadb
      - MYSQL_PASSWORD=mariadb
    ports:
      - 3306:3306
    volumes:
      - ./data:/var/lib/mysql
  app:
    image: ghcr.io/bjornarron/flask-example:latest
    expose:
      - 5000
    environment:
      - DATABASE_URL=mysql+pymysql://mariadb:mariadb@db/mariadb
    depends_on:
      - db
