version: "3"
services:
  db:
    image: postgres:latest
    environment:
      - POSTGRES_ROOT_PASSWORD=mariadb
      - POSTGRESL_DATABASE=mariadb
      - POSTGRES_USER=mariadb
      - POSTGRES_PASSWORD=mariadb
    ports:
      - 5432:5432
    volumes:
      - ./data:/var/lib/mysql
  app:
    image: ghcr.io/jesperjesper/flask-example:latest
    expose:
      - 5000
    depends_on:
      - db
