name: ci pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build Docker image
        run: |
          docker build -t ghcr.io/jesperjesper/flask-example:latest .
      
      - name: Login to container registry
        run: |
          docker login ghcr.io --username jesperjesper --password ${{ secrets.devopsex }}
      
      - name: Push Docker image to container registry
        run: |
          docker push ghcr.io/jesperjesper/flask-example:latest
      
      - name: Deploy to self-hosted runner
        run: |
          docker stop flask-example || true
          docker rm flask-example || true
          docker pull ghcr.io/jesperjesper/flask-example:latest
          docker run -d --name flask-example -p 5000:5000 ghcr.io/jesperjesper/flask-example:latest
