name: ci pipeline

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build and Push Docker image
        run: |
          sudo docker build -t ghcr.io/jesperjesper/flask-example:latest .
          sudo docker login ghcr.io --username jesperjesper--password ${{ secrets.devopsex }}
          sudo docker push ghcr.io/jesperjesper/flask-example:latest
