name: Ci pipeline 

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Install Python
      run: sudo apt-get update && sudo apt-get install -y python3

    - name: Install Requirements
      run: pip3 install -r requirements.txt

    - name: Run Application
      run: python3 app.py
