name: Docker Build

on:
  push:
    branches: 
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: pyton update
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: pip upgrade
        run: |
          python -m pip install --upgrade pip
      - name: Set up Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose
      - name: Build and run Docker Compose
        run: docker-compose up -d
     # - name: Build Docker image
      #  run: docker build -t app:latest .
